### ISSUE TITLE
Collection view with UIRefrshControl flashing 

### ISSUE THREAD

**Issue by PodsTester-iOS** [airbnb/MagazineLayout#57] opened 2019-11-04 12:38 UTC
**Describe the bug**
I've found weird flickering/flashing animation when collection view is updating using refresh control. Also this issue can be reproduced only on OS 13 and with dynamic height of  "sizeModeForItemAt".

**To Reproduce**
1. Add collection view with MagazineLayout(). 
2. Subscribe on UICollectionViewDelegateMagazineLayout
3. Select "fullWidth(respectsHorizontalInsets: true)", "heightMode: .dynamicAndStretchToTallestItemInRow" for the sizeModeForItemAt
4. Create MagazineLayoutCollectionViewCell
5. Add Refresh control to the collection view
6. Add target to refresh control with collectionView.reloadData()
7. Pull to refresh and see some collectionView content is fleshing

**Screenshots**

**Smartphone (please complete the following information):**
 - Device/Simulator: Any simulator or device
 - OS: Can be reproduced only for iOS 13
 - Version of the MaganizeLayout 1.5.2

**Additional context**
Here is the test project with everything that needed to reproduce this bug:
https://drive.google.com/file/d/1gIHftMHvhpGY4IZgqpM3cUxHtcVnU-Lh/view?usp=sharing
or modified MagazineLayout example:
https://drive.google.com/file/d/1mp9rF7f_X6BWdQRjos18JptzfPrUcjVf/view?usp=sharing

Here is the video with bug:
https://drive.google.com/file/d/1gHRjcuSZz9k7pGqZqxr9GAjF4MC_2-DR/view?usp=sharing

**Comment by bryankeller** [comment] 2019-12-27 15:51
Thanks @PodsTester-iOS - I can reproduce this with `UICollectionViewFlowLayout` at well. My guess is that this is a regression on Apple's end.

For what it's worth, I've seen glitchy behavior with refresh controls in tons of different apps. It wouldn't surprise me if its implementation is glitchy in general!

---

Since this is an issue with flow layout as well, I'm marking this as won't fix.

**Closed by bryankeller** 2019-12-27 15:51 UTC
Labels: wontfix
